export * from "./Facebook.svg";
export * from "./Heart.svg";
export * from "./Instagram.svg";
export * from "./Logo.svg";
export * from "./MagnifyingGlass.svg";
export * from "./Reddit.svg";
export * from "./ShoppingCartSimple.svg";
export * from "./User.svg";
export * from "./Youtube.svg";
